language: haskell

install:
    - cabal update
    - cabal install hspec-shouldbe
    - cd ncursesw && cabal install && cd ..
    - git clone https://github.com/sol/libmpd-haskell && cd libmpd-haskell && cabal install && cd ..
    - git clone https://github.com/sol/hspec-find-specs && cd hspec-find-specs && cabal install && cd ..
    - cabal install
