language: haskell

before_install:
    - cabal install c2hs
    - cd ncursesw && cabal install && cd ..
    - git clone https://github.com/sol/libmpd-haskell && cd libmpd-haskell && cabal install && cd ..
