language: haskell

install:
    - cabal update
    - cabal install hspec-shouldbe hspec-discover
    - cd ncursesw && cabal install && cd ..
    - git clone https://github.com/sol/libmpd-haskell && cd libmpd-haskell && cabal install && cd ..
    - cabal install
